### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ajeetdsouza** [rust-cli/roff-rs#11]
`roff-rs` has had quite a few new feature additions since the previous release, I was wondering when we could expect v0.2?

For context: I've been considering using it for manpage generation for [`zoxide`](https://github.com/ajeetdsouza/zoxide). I also noticed that [`ultraman`](https://github.com/yukihirop/ultraman/blob/c5d1f030a5b01a41815019fef09612ca51013e79/Cargo.toml#L35) uses it for the same reason, but has to rely on the master branch of `roff-rs` rather than on a stable release.

**Comment by epage** [comment]
0.2 has been released.  As a heads up,. the API changed in #15 to be lower level.  There is work in https://github.com/clap-rs/clap/pull/3174 for a generic clap generator built on top of it.
