### ISSUE TITLE
Example in README is not correct—possible bug in .list()?

### ISSUE THREAD

**Issue by codesections** [rust-cli/roff-rs#5]
The example in the README shows an extra line break in the `man` output that does not actually occur in `man`'s output.

Specifically, the example ends with this code:

```rust 
.section("options", &[
        list(
            &[bold("-n"), ", ".into(), bold("--bits"), "=".into(), italic("BITS")],
            &[
                "Set the number of bits to modify. ",
                "Default is one bit.",
            ]
        ),
    ]);
```

The README _correctly_ states that this will result it this roff code:

```roff
.SH OPTIONS
.TP
.BR \-n ", " \-\-bits =\fIBITS\fR
Set the number of bits to modify.
Default is one bit.
```

However, that roff code will **not** create a line break before "Default".  To do that, the roff code should either be:

```roff
Set the number of bits to modify.
.br
Default is one bit.
```

or 

```roff
.nf
Set the number of bits to modify.
Default is one bit.
.fi
```

I'm not sure if this is a very minor bug in the README or a bug in the `.list` method—is the intent for `.list` to put each item on a new line?

**Comment by epage** [comment]
We no longer provide list, so closing.  See #15
