### ISSUE TITLE
Question: roff parser?

### ISSUE THREAD

**Issue by TornaxO7** [rust-cli/roff-rs#54]
Hi! May I ask if you know any roff parsers for rust?
I'd like to be able to read `.roff` files (or to be more clear: manual files) to for example fetch the sections.

If you don't know any available `roff` parsers, may I ask if you know where I can find the grammar (I hope that there's a context-free-grammar definition for `roff` files)?

![peepoShy](https://github.com/user-attachments/assets/1d971ed1-4fe1-48ba-ac1b-f6dff4c1f3f2)

**Comment by epage** [comment]
I don't know of any off the top of my head and would end up doing the same googling you would.

**Comment by TornaxO7** [comment]
oof, ok. Thank you for the fast response!
