### ISSUE TITLE
Roff::new() does not accept all arguments to .TH

### ISSUE THREAD

**Issue by codesections** [rust-cli/roff-rs#6]
`Roff::new()` is currently set up to accept the name and section number of the man page. 
 However, `.TH` can also accept additional arguments: "the date of this revision of the manual page, where the program it documents came from, and the title of the whole book to which this page belongs to." <https://liw.fi/manpages/>

If `Roff::new()` could accept all of these arguments, it would allow `man` to pass the date/version more easily.  I'll submit a PR that revises `Roff::new()` along these lines; let me know if you'd like me to implement it differently.

**Comment by epage** [comment]
Fixed in #15
