### ISSUE TITLE
Unclear copyright situation

### ISSUE THREAD

**Issue by alexanderkjall** [rust-cli/roff-rs#9]
I'm trying to package this crate for inclusion in debian, but the copyright information is a bit unclear.

The cargo.toml file state that Pascal Hertleif is the author, but LICENSE-MIT state that 'The assert_cli Developers' have copyright.

My guess is that the copyright claim in LICENSE-MIT is incorrect, but it would be great to have that verified.

**Comment by killercup** [comment]
Hah, I guess I forgot to change this when I copied over the license file. Legally, this is fine -- 'the assert_cli developers' at time of copying the file include me and people I know work on Rust CLI projects. I've updated the license to now say 'roff-rs developers' and that is probably also the best thing to use as author. The metadata in the Cargo.toml doesn't include every contributor. I hope that works for you.
